/**
 * Phase 6.2 — device provisioning helpers.
 *
 * Generates unique device_uid (SMF-XXXXXX, hex, 6 chars) and MQTT
 * password (32-char base64-derived), with server-side collision check
 * against iot_nodes.device_uid.
 *
 * Password is generated ONCE per device and returned in plaintext by
 * the provisioning server action for one-time display to the user.
 * Server stores bcrypt hash + password_prefix (4-char) only.
 */

import { createHash, randomBytes } from "crypto";
import bcrypt from "bcryptjs";
import type { SupabaseClient } from "@supabase/supabase-js";

const DEVICE_UID_PREFIX = "SMF-";
const DEVICE_UID_HEX_LEN = 6;
const MQTT_PASSWORD_LEN = 32;
const BCRYPT_ROUNDS = 10;
const MAX_UID_ATTEMPTS = 8;

export type ProvisionedCredentials = {
  device_uid: string;
  mqtt_username: string;
  mqtt_password: string; // plaintext — return once, never store
  mqtt_password_prefix: string;
  mqtt_password_hash: string;
  mqtt_topic_prefix: string; // smf/{customer_uuid}/{device_uid}
};

/** Random 6-char uppercase hex, e.g. "A3F2B1" */
function randomHex(bytes: number): string {
  return randomBytes(bytes).toString("hex").toUpperCase();
}

/** URL-safe base64, 32 chars — stripped of confusing chars */
function randomPassword(len: number): string {
  const raw = randomBytes(48).toString("base64");
  return raw.replace(/[+/=lIO0]/g, "").slice(0, len);
}

/**
 * Generate device_uid with server-side collision check.
 * Returns fresh UID, or throws after MAX_UID_ATTEMPTS.
 */
export async function generateUniqueDeviceUid(admin: SupabaseClient): Promise<string> {
  for (let attempt = 0; attempt < MAX_UID_ATTEMPTS; attempt++) {
    const uid = DEVICE_UID_PREFIX + randomHex(DEVICE_UID_HEX_LEN / 2);
    const { data } = await admin
      .from("iot_nodes")
      .select("id")
      .eq("device_uid", uid)
      .maybeSingle();
    if (!data) return uid;
  }
  throw new Error("device_uid generation exhausted attempts");
}

/**
 * Build a fresh credential set — password generated + hashed here,
 * NOT persisted. Caller inserts device_credentials row using returned
 * hash + prefix, and returns plaintext to UI once.
 */
export async function generateDeviceCredentials(
  device_uid: string,
  customer_identity_id: string
): Promise<ProvisionedCredentials> {
  const mqtt_username = device_uid; // convention: device_uid == mqtt_username
  const mqtt_password = randomPassword(MQTT_PASSWORD_LEN);
  const mqtt_password_prefix = mqtt_password.slice(0, 4);
  const mqtt_password_hash = await bcrypt.hash(mqtt_password, BCRYPT_ROUNDS);
  const mqtt_topic_prefix = `smf/${customer_identity_id}/${device_uid}`;
  return {
    device_uid,
    mqtt_username,
    mqtt_password,
    mqtt_password_prefix,
    mqtt_password_hash,
    mqtt_topic_prefix,
  };
}

/**
 * SHA-256 of plaintext — for logs / audit (never for auth).
 */
export function sha256Hex(plain: string): string {
  return createHash("sha256").update(plain).digest("hex");
}

/**
 * Build the ready-to-flash secrets.h content.
 * Used by the provisioning UI download button.
 */
export function buildSecretsHFile(creds: ProvisionedCredentials, customer_identity_id: string): string {
  return [
    "// secrets.h — auto-generated by SMF IoT device provisioning",
    "// DO NOT COMMIT. Move to firmware/main_board/include/secrets.h",
    "// Device UID: " + creds.device_uid,
    "// Generated at: " + new Date().toISOString(),
    "#pragma once",
    "",
    "// Phase 6.1 multi-tenant topic model — device confined to own prefix.",
    "#define MQTT_CUSTOMER_ID   \"" + customer_identity_id + "\"",
    "#define MQTT_DEVICE_UID    \"" + creds.device_uid + "\"",
    "",
    "// MQTT credentials — device-unique. ACL locks device to own topic.",
    "#define MQTT_USER          \"" + creds.mqtt_username + "\"",
    "#define MQTT_PASSWORD      \"" + creds.mqtt_password + "\"",
    "",
    "// Optional: RS485 Modbus soil probe. Set true only if wired.",
    "#define SOIL_MODBUS_ENABLED false",
    "",
  ].join("\n");
}

/**
 * Build shell command the operator runs on VPS to activate the device
 * in EMQX (fallback if webhook unavailable). Idempotent.
 */
export function buildEmqxActivationCommand(
  creds: ProvisionedCredentials,
  customer_identity_id: string
): string {
  return [
    "sudo /opt/smf-iot/emqx/create-device.sh",
    "'" + creds.device_uid + "'",
    "'" + creds.mqtt_password + "'",
    "'" + customer_identity_id + "'",
  ].join(" ");
}

/**
 * Call the provisioning webhook on the VPS to auto-create EMQX user + ACL.
 * Requires env vars PROV_WEBHOOK_URL + PROV_WEBHOOK_TOKEN.
 * Returns {ok:true} on success (idempotent — safe to retry).
 */
export type WebhookActivationResult =
  | { ok: true; user: string; acl_rules: number; cached?: boolean }
  | { ok: false; error: string };

export async function activateOnEmqxWebhook(
  creds: ProvisionedCredentials,
  customer_identity_id: string
): Promise<WebhookActivationResult> {
  const url = process.env.PROV_WEBHOOK_URL;
  const token = process.env.PROV_WEBHOOK_TOKEN;
  if (!url || !token) {
    return { ok: false, error: "PROV_WEBHOOK_URL / PROV_WEBHOOK_TOKEN not configured" };
  }

  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);

  try {
    const res = await fetch(url, {
      method: "POST",
      headers: {
        authorization: "Bearer " + token,
        "content-type": "application/json",
      },
      body: JSON.stringify({
        op: "provision-device",
        device_uid: creds.device_uid,
        mqtt_password: creds.mqtt_password,
        customer_uuid: customer_identity_id,
      }),
      signal: controller.signal,
    });
    const body: unknown = await res.json().catch(() => ({}));
    const bodyObj = body as { ok?: boolean; error?: string; user?: string; acl_rules?: number; cached?: boolean };
    if (!res.ok || !bodyObj.ok) {
      return { ok: false, error: bodyObj.error ?? "webhook http " + res.status };
    }
    return {
      ok: true,
      user: bodyObj.user ?? "unknown",
      acl_rules: bodyObj.acl_rules ?? 0,
      cached: bodyObj.cached,
    };
  } catch (e) {
    return { ok: false, error: "webhook call failed: " + (e as Error).message };
  } finally {
    clearTimeout(timeout);
  }
}
